spring:
    datasource:
        url: jdbc:mysql://localhost:3306/codemasters_school_project
        username: root
        password: Tshimologong2023
        driver-class-name: com.mysql.cj.jdbc.Driver
        
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
            database: mysql
            database-platform: org.hibernate.dialect.MySQLDialect

    mail:
        host: smtp.gmail.com
        port: 465
        username: codemasters2023@gmail.com
        password: dyxx llmv iwpj ncpn
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        enable: true